name: Build and Push Backend

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'    

jobs:
  build:
    env:
       GITHUB_SHA: ${{ github.sha }}
       ECR_REGISTRY: 354918400547.dkr.ecr.us-east-2.amazonaws.com
       ECR_REPOSITORY: backend
       CLUSTER_NAME: 3tier-application-cluster
       SERVICE_NAME: backend-service  
       CONTAINER_NAME: backend-container
       AWS-region: us-east-2
    runs-on: ubuntu-latest

    permissions:
      id-token: write  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::354918400547:role/ECR-github-role  
          aws-region: ${{ env.AWS-region }}
          audience: sts.amazonaws.com  
          
      - name: Login to Amazon ECR
        run: |
          echo "Logging in to Amazon ECR..."
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 354918400547.dkr.ecr.us-east-2.amazonaws.com
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build, Tag, and Push Docker image to ECR
        run: |
          IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA")
          
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./backend
          
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest

          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $ECR_REGISTRY
        
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
          
      - name: Update ECS Task Definition
        run: |
          # Fetch the current task definition
          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition $SERVICE_NAME --region $AWS-region)

          # Create a new task definition with the updated image
          NEW_TASK_DEF=$(echo $TASK_DEFINITION | jq --arg IMAGE "$ECR_REGISTRY/$ECR_REPOSITORY:latest" \
          '.taskDefinition | .containerDefinitions[0].image=$IMAGE')

          # Register the new task definition revision
          echo "$NEW_TASK_DEF" > new-task-def.json
          aws ecs register-task-definition --cli-input-json file://new-task-def.json --region $AWS-region
