name: Build and Push Backend

on:
  push:
    paths:
      - 'backend/**'   # This triggers the workflow when changes are pushed to the 'backend' directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::354918400547:role/ECR-github-role  # Your IAM role
          aws-region: us-east-2  # Adjust this to your desired region

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t backend ./backend  # Path to your backend Dockerfile

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 354918400547.dkr.ecr.us-east-2.amazonaws.com

      - name: Tag Docker image for ECR
        run: |
          docker tag backend:latest 354918400547.dkr.ecr.us-east-2.amazonaws.com/backend:latest

      - name: Push Docker image to ECR
        run: |
          docker push 354918400547.dkr.ecr.us-east-2.amazonaws.com/backend:latest
