name: Build and Push Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'  # Only trigger when files in the frontend directory change

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::354918400547:role/Github-repo-and-ECR
          aws-region: us-east-2

      - name: Build Docker image
        run: |
          docker build -t frontend ./frontend

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 354918400547.dkr.ecr.us-east-2.amazonaws.com

      - name: Tag and Push Docker image to ECR
        run: |
          docker tag frontend:latest 354918400547.dkr.ecr.us-east-2.amazonaws.com/frontend:latest
          docker push 354918400547.dkr.ecr.us-east-2.amazonaws.com/frontend:latest
